---
- name: Controller Configuration
  hosts: localhost
  gather_facts: false

  vars_files:
    - desired_state/job_templates.yml

  vars:
    controller_host: https://aap.example.com
    controller_username: admin
    controller_password: password

  tasks:

    - import_tasks: tasks/apply.yml

    - import_tasks: tasks/drift.yml