---
- hosts: localhost
  gather_facts: false

  roles:
    - role: kevin_enterprise.estudo.system_report


  tasks:

    - name: Teste
      kevin_enterprise.estudo.meu_modulo:
        nome: Neymar
        token: "meu-token-secreto"
        aws_account: "123456789012"
        accounts:
          - "123456789012"
          - "210987654321"
        action: "start"
        config:
          host: opa.local
          port: 8181

      register: resultado

    - debug:
        var: resultado

    - debug:
        var: resultado.msg

    - set_stats:
        data:
          compliance_result: "iuup"

    - debug:
        msg: "{{ resultado.account_id | kevin_enterprise.estudo.mask_account }}"