---
- name: Coletar informações da máquina
  hosts: all
  gather_facts: yes
  
  tasks:
    - name: Exibir o sistema operacional
      debug:
        msg: "O SO é {{ ansible_distribution }} {{ ansible_distribution_version }}"

    - name: Exibir memória total
      debug:
        msg: "Memória total: {{ ansible_memtotal_mb }} MB"
