---
- name: Coletar informações da máquina
  hosts: all
  gather_facts: yes
  
  tasks:
    - name: Exibir o sistema operacional
      debug:
        msg: "O SO é {{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_version'] }}"

    - name: Exibir memória total
      debug:
        msg: "Memória total: {{ ansible_facts['memtotal_mb'] }} MB"
