---
- name: Coletar informações da máquina
  hosts: all
  gather_facts: yes  # Ativa a coleta de informações (facts)
  
  tasks:
    - name: Exibir o sistema operacional
      ansible.builtin.debug:
        msg: "O SO é {{ ansible_distribution }} {{ ansible_distribution_version }}"

    - name: Exibir o endereço IP
      ansible.builtin.debug:
        msg: "O IP é {{ ansible_default_ipv4.address }}"

    - name: Exibir memória total
      ansible.builtin.debug:
        msg: "Memória total: {{ ansible_memtotal_mb }} MB"

