# inventory.ini

[local]
localhost ansible_connection=local

[ec2]
minha-instancia ansible_host=i-0099135bd68bd9eaa

[ec2:vars]
ansible_connection=amazon.aws.aws_ssm
ansible_aws_ssm_region=us-east-1
ansible_aws_ssm_bucket_name=teste-poc-estudo
ansible_python_interpreter=/usr/bin/python3