# playbook.yml
- name: Exemplo via SSM
  hosts: ec2
  gather_facts: true
  tasks:
    - name: Verifica o hostname
      command: hostname
      register: result

    - name: Exibe resultado
      debug:
        msg: "{{ result.stdout }}"